from __future__ import print_function

import os

import numpy as np
import pytest
from asaptools import simplecomm as sc, timekeeper

from pyaverager import average_types, climAverager, climFileIO

timer = timekeeper.TimeKeeper()

series_directory = 'tests/data/series_files/atm/'
series_file_pattern = ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix']
series_date_pattern = 'yyyymm-yyyymm'
series_suffix = '.nc'

slice_directory = 'tests/data/slice_files/atm/'
slice_file_pattern = ['$prefix', '.', '$date_pattern', '$suffix']
slice_suffix = '.nc'

prefix = 'test_data.cam.h0'
split = 'False'
split_fn = ''

series_hist_dict = {
    1: {
        0: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 1,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 2,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 3,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 4,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 5,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 6,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 7,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 8,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 9,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 10,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 11,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    2: {
        0: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 12,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 13,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 14,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 15,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 16,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 17,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 18,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 19,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 20,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 21,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 22,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 23,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    3: {
        0: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 24,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 25,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 26,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 27,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 28,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 29,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 30,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 31,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 32,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 33,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 34,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 35,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    4: {
        0: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 36,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 37,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 38,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 39,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 40,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 41,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 42,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 43,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 44,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 45,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 46,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 47,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    5: {
        0: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 48,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 49,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 50,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 51,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 52,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 53,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 54,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 55,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 56,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 57,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 58,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/series_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 59,
            'date_stamp': '000101-000512',
            'pattern': ['$prefix', '.', '$var', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    6: {},
}
series_series_list = [
    'var.07',
    'var.10',
    'var.04',
    'var.08',
    'var.05',
    'var.09',
    'time__meta',
    'var.06',
    'var.01',
    'var.03',
    'var.02',
]
series_meta_list = ['lev', 'lat', 'lon']
series_key = 'hi'

slice_hist_dict = {
    1: {
        0: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0001-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    2: {
        0: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0002-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    3: {
        0: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0003-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    4: {
        0: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0004-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    5: {
        0: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/atm/',
            'fn': 'test_data.cam.h0',
            'index': 0,
            'date_stamp': '0005-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    6: {},
}
slice_series_list = [
    'time__meta',
    'var.01',
    'var.02',
    'var.03',
    'var.04',
    'var.05',
    'var.06',
    'var.07',
    'var.08',
    'var.09',
    'var.10',
]
slice_meta_list = ['lev', 'lat', 'lon']
slice_key = 'time__meta'

ocean_slice_hist_dict = {
    1: {
        0: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0001-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    2: {
        0: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0002-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    3: {
        0: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0003-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    4: {
        0: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0004-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    5: {
        0: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-01',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        1: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-02',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        2: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-03',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        3: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-04',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        4: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-05',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        5: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-06',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        6: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-07',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        7: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-08',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        8: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-09',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        9: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-10',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        10: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-11',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
        11: {
            'directory': 'tests/data/slice_files/ocn/',
            'fn': 'test_data.pop.h',
            'index': 0,
            'date_stamp': '0005-12',
            'pattern': ['$prefix', '.', '$date_pattern', '$suffix'],
            'suffix': '.nc',
        },
    },
    6: {},
}


@pytest.mark.parametrize(
    'var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave',
    [
        (
            'var01',
            slice_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5,
        ),
        (
            'var01',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.5,
        ),
        (
            'var01',
            series_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5,
        ),
        (
            'var01',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.5,
        ),
        (
            'var02',
            slice_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5,
        ),
        (
            'var02',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.5,
        ),
        (
            'var02',
            series_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5,
        ),
        (
            'var02',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.5,
        ),
    ],
)
def test_avg_var(var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave):

    depend = False
    split = False
    file_dict, open_list = climFileIO.open_all_files(
        hist_dict, months_to_average, years, var, split, ave_type, depend, fyr
    )

    calc = climAverager.avg_var(
        var, years, hist_dict, ave_info, file_dict, ave_type, timer, depend, fyr
    )
    assert np.array_equal(calc, np.full(calc.shape, ave))

    climFileIO.close_all_files(open_list)


@pytest.mark.parametrize(
    'var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave',
    [
        (
            'var01',
            slice_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5.1,
        ),
        (
            'var01',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.526029,
        ),
        (
            'var01',
            series_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5.1,
        ),
        (
            'var01',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ya',
            average_types.average_types['ya'],
            1,
            32.63014,
        ),
        (
            'var01',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.526029,
        ),
        (
            'var02',
            slice_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5.1,
        ),
        (
            'var02',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.526029,
        ),
        (
            'var02',
            series_hist_dict,
            [11, 0, 1],
            [2, 3, 4],
            'djf',
            average_types.average_types['djf'],
            1,
            5.1,
        ),
        (
            'var02',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ya',
            average_types.average_types['ya'],
            1,
            32.63014,
        ),
        (
            'var02',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'ann',
            average_types.average_types['ann'],
            1,
            6.526029,
        ),
    ],
)
def test_weighted_avg_var(var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave):

    depend = False
    split = False
    file_dict, open_list = climFileIO.open_all_files(
        hist_dict, months_to_average, years, var, split, ave_type, depend, fyr
    )

    calc = climAverager.weighted_avg_var(
        var, years, hist_dict, ave_info, file_dict, ave_type, timer, depend, fyr
    )
    print(calc)
    assert np.array_equal(
        np.round_(calc, decimals=0), np.round_(np.full(calc.shape, ave), decimals=0)
    )

    climFileIO.close_all_files(open_list)


@pytest.mark.parametrize(
    'var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave1, ave2, ave3',
    [
        (
            'var02',
            ocean_slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [2],
            'hor.meanConcat',
            average_types.average_types['hor.meanConcat'],
            1,
            1.0,
            [-33.61257, -33.64239, -33.693497, -33.73702],
            0.0,
        ),
    ],
)
def test_mean_diff_rms(
    var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave1, ave2, ave3
):

    depend = False
    split = False
    obs_file = 'tests/data/timeseries_obs/obs.nc'
    reg_obs_file = 'tests/data/timeseries_obs/ocean_hor_mean_obs.nc'
    file_dict, open_list = climFileIO.open_all_files(
        hist_dict, months_to_average, years, var, split, ave_type, depend, fyr
    )

    calc1, calc2, calc3 = climAverager.mean_diff_rms(
        var,
        'ocean',
        1,
        'REGION_MASK',
        'TAREA',
        years,
        hist_dict,
        ave_info,
        file_dict,
        obs_file,
        reg_obs_file,
        None,
        True,
        9999,
        9999,
        4,
    )
    assert np.array_equal(
        np.round_(calc1, decimals=0), np.round_(np.full(calc1.shape, ave1), decimals=0)
    )
    assert np.array_equal(np.round_(calc2, decimals=0), np.round_(np.array(ave2), decimals=0))
    assert np.array_equal(
        np.round_(calc3, decimals=0), np.round_(np.full(calc3.shape, ave3), decimals=0)
    )

    climFileIO.close_all_files(open_list)


@pytest.mark.parametrize(
    'var, hist_dict, months_to_average, years, collapse_dim, ave_type, ave_info, fyr, ave',
    [
        (
            'var01',
            slice_hist_dict,
            [11],
            [2],
            'lon',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            12.0,
        ),
        (
            'var01',
            series_hist_dict,
            [11],
            [3],
            'lon',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            12.0,
        ),
        (
            'var02',
            slice_hist_dict,
            [0],
            [4],
            'lon',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            1.0,
        ),
        (
            'var02',
            series_hist_dict,
            [1],
            [2],
            'lon',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            2.0,
        ),
        (
            'var01',
            slice_hist_dict,
            [11],
            [2],
            '5<lon<10',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            12.0,
        ),
        (
            'var01',
            series_hist_dict,
            [11],
            [3],
            '5<lon<10',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            12.0,
        ),
        (
            'var02',
            slice_hist_dict,
            [0],
            [4],
            '5<lon<10',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            1.0,
        ),
        (
            'var02',
            series_hist_dict,
            [1],
            [2],
            '5<lon<10',
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            2.0,
        ),
    ],
)
def test_zonal_average(
    var, hist_dict, months_to_average, years, collapse_dim, ave_type, ave_info, fyr, ave
):

    depend = False
    split = False
    file_dict, open_list = climFileIO.open_all_files(
        hist_dict, months_to_average, years, var, split, ave_type, depend, fyr
    )

    calc = climAverager.zonal_average(
        var, years[0], months_to_average[0], hist_dict, file_dict, timer, collapse_dim
    )
    print(calc)
    assert np.array_equal(
        np.round_(calc, decimals=0), np.round_(np.full(calc.shape, ave), decimals=0)
    )

    climFileIO.close_all_files(open_list)


@pytest.mark.parametrize(
    'var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave',
    [
        (
            'var01',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            6.526029,
        ),
        (
            'var01',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            32.63014,
        ),
        (
            'var02',
            slice_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            6.526029,
        ),
        (
            'var02',
            series_hist_dict,
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [1, 2, 3, 4, 5],
            'zonalavg',
            average_types.average_types['zonalavg'],
            1,
            32.63014,
        ),
    ],
)
def test_time_concat(var, hist_dict, months_to_average, years, ave_type, ave_info, fyr, ave):

    depend = False
    split = False
    serial = True

    l_master = True
    serial = True
    var_list = [
        'var01',
        'var02',
        'var03',
        'var04',
        'var05',
        'var06',
        'var07',
        'var08',
        'var09',
        'var10',
        'hi',
        'aice',
    ]
    lvar_list = [
        'var01',
        'var02',
        'var03',
        'var04',
        'var05',
        'var06',
        'var07',
        'var08',
        'var09',
        'var10',
        'hi',
        'aice',
    ]
    meta_list = ['lat', 'lon', 'lev']
    hist_dict = slice_hist_dict
    hist_type = 'slice'
    ave_descr = ['ya', '1']
    prefix = 'test_data.cice.h'
    outfile = 'test_data.cice.h.0001.nc'
    split = False
    split_name = ''
    out_dir = 'tests/output/climAverager/'
    simplecomm = sc.create_comm(serial=True)
    nc_formt = 'netcdf4'
    month = 0
    key = 'var02'
    clobber = True
    firstYr = 1
    endYr = 1
    ave_date = '0001'

    file_dict, open_list = climFileIO.open_all_files(
        hist_dict, months_to_average, years, var, split, ave_type, depend, fyr
    )

    all_files_vars, new_file = climFileIO.define_ave_file(
        l_master,
        serial,
        var_list,
        lvar_list,
        meta_list,
        hist_dict,
        hist_type,
        ave_descr,
        prefix,
        outfile,
        split,
        split_name,
        out_dir,
        simplecomm,
        nc_formt,
        month,
        key,
        clobber,
        firstYr,
        endYr,
        ave_date,
        pre_proc_attr=None,
        pre_proc_variables=None,
        collapse_dim='',
    )

    assert os.path.isfile(out_dir + '/' + outfile) is True

    climFileIO.close_all_files(open_list)
